### ISSUE TITLE
What's the point of `SkimItem`s with non-static lifetime?

### ISSUE THREAD

**Issue by kimono-koans** [kimono-koans/two_percent#13]
> What's the point of `SkimItem`s with non-static lifetime? The items are already passed around as `Arc<dyn SkimItem>` which has a static lifetime anyway, and this breaks the ability to downcast the items (because you can't downcast them), as seen [in the downcast example which no longer downcasts the items and instead uses the `.text()` method from the trait](https://github.com/kimono-koans/two_percent/blob/vendored/examples/downcast.rs#L43).

_Originally posted by @idanarye in https://github.com/kimono-koans/two_percent/issues/11#issuecomment-2258304438_

**Comment by kimono-koans** [comment]
> What's the point of SkimItems with non-static lifetime? The items are already passed around as Arc<dyn SkimItem> which has a static lifetime anyway

I believe the idea was to reduce memory usage after a `skim` invocation, which was a major issue for `httm`.

I won't tell you this works as expected.  The idea was to rip out all static lifetimes everywhere in `skim`.  `httm` was still holding onto lots of memory after a `skim` invocation, whereas now it doesn't.  I'm sure now much of this was down to the design of my `SkimItems`.

I suppose strict API compatibility is/was not a goal of mine and downcast was not a feature I was especially interested in or used.  `two_percent`, to the extent I work on it, serves `httm`.  I/it may have been misguided, but FYI my priority was/is memory usage after invocation (which I can also imagine could be an issue for other library users).  After tearing much of this out, I came to understand that the `'static` lifetime is implicit re: these boxed trait objects, which I probably didn't at the time.

So -- you're not collaborating with a Rust genius (or even a professional programmer!)  Feel free to question my decisions.  And, if you want downcast and are using it, please feel to add back in a feature branch, so I can test with `httm`.

**Comment by idanarye** [comment]
I see that httm only implements `SkimItem` for `SelectionCandidate`. Mind if I try parametrizing `Skim` (and most of the other types, really) to take the concrete type as generic parameter? That should improve performance for everyone.

**Comment by kimono-koans** [comment]
> I see that httm only implements SkimItem for SelectionCandidate. Mind if I try parametrizing Skim (and most of the other types, really) to take the concrete type as generic parameter? That should improve performance for everyone.

Yeah, that'd be great.  Give it a shot.

My feeling re: any `skim` API is: Can we easily refactor our app code?  Because I'm not sure `sk` is being developed and used by anyone else.  If I or they want to port my/your changes back, that's great, but I don't see anything happening re: `skim`.

*Dozens of things* are more important to me, ... like competing with `fzf`.  See: https://github.com/lotabout/skim/issues/561

`fzf` is truly impressive but `skim` should be faster and use less memory, and if we are calling `skim` as a library, when we return from running `skim`, I'd like that memory back.

**Comment by idanarye** [comment]
Okay. I can also add something like this, as a fallback:

```rust
#[derive(Clone)]
struct DynamicSkimItem(pub Arc<dyn SkimItem>);

impl DynamicSkimItem {
    pub fn new(item: impl 'static + SkimItem) -> Self {
        Self(Arc::new(item))
    }
}

impl SkimItem for DynamicSkimItem {
    ...
}
```

**Comment by idanarye** [comment]
Wait - does Skim clone it alot? I assume it does - otherwise it'd use `Box` instead of `Arc`. Maybe It's better to keep it as `Arc<T: SkimItem>`?

**Comment by kimono-koans** [comment]
> Wait - does Skim clone it alot? I assume it does - otherwise it'd use Box instead of Arc. Maybe It's better to keep it as Arc<T: SkimItem>?

It needs to be an `Arc` for a few reasons.  Yes, `two_percent` dedups using clone.  It also needs to be `Send + Sync` as ingest uses `crossbeam` queues on at least two threads.

**Comment by idanarye** [comment]
I'm going to have to remove this method:

https://github.com/kimono-koans/two_percent/blob/9d50cad7e01f63f78df54953e75c4e45264cff1e/src/item.rs#L73-L75

This mostly means that places that treated released data as empty strings will need to change. I don't think the behavior itself is going to change much, because this was already kind of an error...

**Comment by idanarye** [comment]
Ran into a problem. The `Default` for `SkimOptions` assigns to `cmd_collector` a `SkimItemReader`, which converts deep down converts text to `DefaultSkimItem` (or `Box<str>`) using:

https://github.com/kimono-koans/two_percent/blob/96492471a9940efb1c855edb5f0cd5c27ba4ff6f/src/helper/ingest.rs#L95-L127

This is not something I can make generic, because that will require any implementation of `SkimItem` to be `FromStr` (or have something with similar semantics) which is not rally suitable for custom skim items.

I may have to settler for restoring `'static + Any`...

**Comment by kimono-koans** [comment]
https://github.com/kimono-koans/two_percent/pull/14
