### ISSUE TITLE
Make `vendored` the default branch of this repository

### ISSUE THREAD

**Issue by idanarye** [kimono-koans/two_percent#15]
Since `master` is just the untouched code from the original skim repository, it makes more sense to make the actual branch, `vendored`, the default branch.

**Comment by kimono-koans** [comment]
This sounds fine, but imagine `skim` decides to start development again, I want to be able to merge their new PRs incrementally.  I'm not sure this is possible with a fork, but I think works with a branch.  So I'd like to make sure I don't have to accept all changes at once, or I can merge to the local `master` and pull incrementally from there.   

Do you know any better about how this works?

**Comment by idanarye** [comment]
I don't mean you should move the work to the `master` branch. What I mean is to go to the repository's settings and under the _General_ tab change _Default branch_ from `master` to `vendored`. What this will do is:

1. Change the default branch displayed in https://github.com/kimono-koans from `master` to `vendored`.
2. When cloning the repository, `vendored` will be checked out by default instead of `master`.
3. When forking the repository, the "Copy the `master` branch only" checkbox will change to "Copy the `vendored` branch only"

You'll still have a `master` branch that will remain the same as the upstream `master` branch, and you could still use that branch to sync with the original Skim if they start development again. All that change will do is make GitHub treat `vendored` as the main development branch of this repository.

**Comment by kimono-koans** [comment]
Okay, it's been done.  We will see how it works out.
